---
title: "Introduction to the EES 3310/5310 Laboratories"
author: "Jonathan Gilligan"
date: "Reading for Lab August 27, 2018"
fontfamily: "newtxtext,newtxmath"
fontsize: "12pt"
output:
  pdf_document: default
  html_document: default
  github_document: default
---
# Overview of EES 3310/5310 Labs

The laboratories in this course are computational. My goals for the laboratory section are:

1. Learn about best practices for _reproducible research_ and get experience applying tools and methods for making 
   sure that your research is reliable, reproducible, and trustworthy.
   We will focus on research about climate science and climate and energy policy, but the methods and tools we will
   use are widely used in all kinds of research in natural and social sciences and also in the private sector.
2. Get experience working with real data: download and analyze data and report the results of your analysis.
3. Get experience working with computer models of different aspects of the climate system. Learn how to use models
   to do science, how to analyze and interpret the results of model simulations, and how to write reports about
   research using computational models.

## General Policies

* There will be **two** web resources for each lab: 
    * **Documentation** that describes the lab and tells you what you need to do to prepare and what you will do in the 
      lab class.
    * **An assignment** that provides a template you will use in carrying out the lab and writing it up. The assignment
      will consist of a web link for you to click on to accept the assignment in GitHub Classroom. After you accept
      the assignment, GitHub Classroom will copy the assignment into your own GitHub Classroom account.
      You will then clone the assignment from GitHub to your own computer or a computer in the lab classroom to work
      on it.

    Both the documentation and the assignment will be posted to the course web site at 
    <https://ees3310.jgilligan.org/schedule/> at least one week before the lab class.
* **Before** coming to lab:
    * Be sure to read the documentation for that week's lab.
    * Accept the assignment on GitHub Classroom (click on the Assignment link in the course web site). If you will be
      bringing your own computer to the lab, you may want to clone the assignment onto your own computer before you
      come to lab, but that's not strictly necessary. If you will be using one of the computers in the lab classroom,
      you can clone the assignment when you log in at the beginning of class.
      
* In the first lab, on September 27th, Ms. Best will explain all of the different software we will be using and will
  walk you through all the steps of using Git to work with your assignments.
   
## Schedule for the Semester

The semester is divided roughly in half. 

### First Half of the Semester:

In the first half, the readings, class sessions, and laboratories will focus 
on understanding the science of how the earth's climate system works and how human perturbations to the environment may
affect the climate. 

The weekly labs during the first half of the semester will initiially focus on exercises from the book 
_Global Warming: Understanding the Forecast_ 
and then on Sept. 24--Oct. 15 you will work in pairs to develop your own project to investigate a
question about the climate using the computer models and/or data from the major climatic data archives.

#### Extended Lab Project

The project has the following important dates:

* You and your partner will get your research topic approved by Prof. Gilligan or Ms. Best by 
  **Wednesday September 26**.
* You and your partner will present the results of your research project in the lab on **Monday, October 15th**.
* You and your partner will turn in a written report on **Wednesday October 17th**.

### Second Half of the Semester

In the second half of the semester, you will analyze data on the economies and energy use of different countries around
the world and use these to analyze different policy options for reducing greenhouse gas emissions. The labs will begin
with exercises that follow the analyses you will be reading about in the book, _The Climate Fix_, and then 
you and a partner will conduct a detailed analysis of policy options for a country of your choice to make a transition
to a cleaner energy supply.

#### Policy Analysis for a Country

The policy analysis project has the following important dates:

* You and your partner will present the results of your policy analysis in the lab on **Monday December 3rd**.
* You and your partner will turn in a written policy analysis report on **Wednesday December 5th**.


# Laboratory Classroom

The laboratory will meet in [Stevenson 2200](https://as.vanderbilt.edu/vuit/computer_services/facilities/Stevenson.php) 
(right next to the Science and Engineering Library). This classroom is
equipped with computers that have all the software you need for this class. You are also free to bring your own
laptop to the lab. Detailed instructions for installing R, RStudio, git, and (optionally) the LaTeX typesetting
system on your computer (for Windows, MacOs, and Linux) are available on the course web site at 
<https://ees3310.jgilligan.org/tools/>.

The computer laboratory is accessible using your Vanderbilt ID card 24/7 except when other classes are meeting there.
You can check the availability of the computer lab using Vanderbilt's 
[VirtualEMS web app](https://emscampus.app.vanderbilt.edu/VirtualEms/LocationDetails.aspx?data=7cZwpiiplNtjoymq%2bO2RAGKuISCBHNPXxVY8ryMN4zGmaUtIip9OXVNLod0VXhr6)
at <https://emscampus.app.vanderbilt.edu/VirtualEms/>.
Be aware that the classroom is used Monday through Thursday evening from 7:00 until 10:00 or 10:30 for Astronomy labs.

# Software Tools

We will use four principal software tools for this class. All four are free and available for Windows, MacOS, and 
Linux. Detailed instructions for downloading and installing them are available on the course web site at
<https://ees3310.jgilligan.org/tools/>:

1. R: statistical analysis software
2. RStudio: a user-friendly interface to R, which makes it much easier to use.
3. Git: a tool for keeping track of revisions in computer code and documents and coordinating working together with
   other people on a project.
4. LaTeX: This is strictly optional. It is a typesetting package that allows you to produce PDF (acrobat) documents
   from RStudio.  If you choose not to install LaTeX, you can still produce HTML (web) and DOCX (Microsoft Word) 
   documents. The downside is that a full LaTeX distribution can be quite large (several hundred megabytes), so if you
   are running low on disk space, you might not want to install it. 
   
     LaTeX is installed on the lab computers, so you will always have the option of producing PDF documents there, even
     if you don't install it on your own computer.

All of this software is installed on the lab computers in Stevenson 2200, so you do not need to install it on your own
computer, but you will need it to do the data analysis and write up your lab reports, so it will probably be convenient
for you to install your own copies.
